#███─████─█───█─████─██─██──█─███─████─███─███
#█───█──█─██─██─█──█──███──██─█───█──█─█────█─
#███─█──█─█─█─█─████───█────█─███─█──█─███──█─
#──█─█──█─█───█─█──█──███───█───█─█──█─█────█─
#███─████─█───█─█──█─██─██──█─███─████─█────█─
#
# Dev: SoMax1soft
# Contact: T.ME/SOMAX1SOFT
# Info: Max1soft.PW
#
# Команда выдачи: /sotrident <nick>
#
# 卐卐 Стянув стянув! 卐卐
#
permission-message: "§cЧё по правам!"
trident-name: "§c§lКрюк Пуджа"
trident-lore:
  - ""
  - "§7Стянув стянув!"
  - ""
trident-actionbar-neuspex: "§сСорвалась рыбка!"
trident-actionbar-todo: "§6Вы притягиваете цель"

trident-actionbar-disable-fly: "§сВыключите флай для использывания!"
trident-actionbar-disable-gm: "§сВыключите ГМ1/ГМ3 для использывания!"
trident-actionbar-disable-god: "§сВыключите режим бога для использывания!"
